#!/usr/bin/env python3
"""Build and check the Oranburg iA Writer template bundles.

iA Writer copies a .iatemplate bundle when it installs it and resolves
every stylesheet, script and image relative to the bundle's
Contents/Resources folder, so nothing inside a bundle may point outside
it. The shared CSS and JavaScript are therefore written once, in
shared/, and copied into each bundle by this script.

Usage (standard library only, macOS /usr/bin/python3 is enough):

    python3 tools/build.py            sync shared/ into every bundle, then check
    python3 tools/build.py --check    check only; exit 1 on any problem
    python3 tools/build.py --bump minor|patch|major
                                      raise CFBundleShortVersionString and
                                      CFBundleVersion in every Info.plist
    python3 tools/build.py --zip      also write dist/<Bundle>.iatemplate.zip
                                      (for iPhone, iPad and Windows installs)

Which shared files a bundle receives is decided by what its HTML and CSS
actually reference, followed transitively through @import.
"""

import argparse
import html.parser
import plistlib
import re
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHARED = ROOT / "shared"
DIST = ROOT / "dist"

BANNER = {
    ".css": "/* GENERATED by tools/build.py from shared/{name}. Edit the shared file, not this copy. */\n",
    ".js": "/* GENERATED by tools/build.py from shared/{name}. Edit the shared file, not this copy. */\n",
}

REQUIRED_KEYS = ("CFBundleName", "CFBundleIdentifier", "IATemplateDocumentFile")
PAGE_KEYS = ("IATemplateDocumentFile", "IATemplateTitleFile",
             "IATemplateHeaderFile", "IATemplateFooterFile")
ALLOWED_DATA = {"data-document", "data-title", "data-author", "data-date",
                "data-page-number", "data-page-count"}
IDENT_RE = re.compile(r"^[A-Za-z0-9.-]+$")
CSS_REF_RE = re.compile(r"""@import\s+(?:url\()?\s*["']?([^"')\s;]+)|url\(\s*["']?([^"')]+)["']?\s*\)""")


def bundles():
    return sorted(p for p in ROOT.glob("*.iatemplate") if p.is_dir())


def resources(bundle):
    return bundle / "Contents" / "Resources"


class RefParser(html.parser.HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.refs = []
        self.data_attrs = set()
        self.has_document = False
        self.stack = []
        self.errors = []

    VOID = {"meta", "link", "br", "hr", "img", "input", "source", "col", "area", "base", "wbr"}

    def handle_starttag(self, tag, attrs):
        for k, v in attrs:
            if k in ("href", "src") and v and tag in ("link", "script", "img"):
                self.refs.append(v)
            if k.startswith("data-") and not k.startswith("data-oranburg-"):
                self.data_attrs.add(k)
            if k == "data-document":
                self.has_document = True
        if tag not in self.VOID:
            self.stack.append(tag)

    def handle_endtag(self, tag):
        if tag in self.VOID:
            return
        if not self.stack or self.stack[-1] != tag:
            self.errors.append(f"unbalanced </{tag}> (open: {self.stack[-3:]})")
            if tag in self.stack:
                while self.stack and self.stack.pop() != tag:
                    pass
            return
        self.stack.pop()


def local_ref(ref):
    return not re.match(r"^[a-z][a-z0-9+.-]*:", ref) and not ref.startswith("#")


def css_refs(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return [a or b for a, b in CSS_REF_RE.findall(text)]


def referenced_files(res):
    """Every local file the bundle's pages need, followed through @import."""
    seen, queue = set(), []
    for page in res.glob("*.html"):
        p = RefParser()
        p.feed(page.read_text(encoding="utf-8"))
        queue += [r for r in p.refs if local_ref(r)]
    while queue:
        ref = queue.pop()
        if ref in seen:
            continue
        seen.add(ref)
        if ref.endswith(".css"):
            src = SHARED / ref if (SHARED / ref).exists() else res / ref
            if src.exists():
                queue += [r for r in css_refs(src.read_text(encoding="utf-8")) if local_ref(r)]
    return seen


def generated_text(src):
    banner = BANNER.get(src.suffix, "").format(name=src.name)
    return banner + src.read_text(encoding="utf-8")


def sync():
    for b in bundles():
        res = resources(b)
        for ref in sorted(referenced_files(res)):
            src = SHARED / ref
            if src.exists():
                dst = res / ref
                text = generated_text(src)
                if not dst.exists() or dst.read_text(encoding="utf-8") != text:
                    dst.write_text(text, encoding="utf-8")
                    print(f"synced  {b.name}/Contents/Resources/{ref}")
        # remove shared copies the bundle no longer references
        wanted = referenced_files(res)
        for f in res.iterdir():
            if (SHARED / f.name).exists() and f.name not in wanted:
                f.unlink()
                print(f"removed {b.name}/Contents/Resources/{f.name}")


def check():
    problems = []
    ids = {}
    for b in bundles():
        name = b.name
        plist_path = b / "Contents" / "Info.plist"
        lint = subprocess.run(["plutil", "-lint", str(plist_path)], capture_output=True, text=True) \
            if sys.platform == "darwin" else None
        if lint is not None and lint.returncode != 0:
            problems.append(f"{name}: plutil -lint failed: {lint.stdout.strip()}")
        with plist_path.open("rb") as fh:
            info = plistlib.load(fh)
        for k in REQUIRED_KEYS:
            if not info.get(k):
                problems.append(f"{name}: Info.plist lacks {k}")
        ident = info.get("CFBundleIdentifier", "")
        if not IDENT_RE.match(ident):
            problems.append(f"{name}: bad CFBundleIdentifier {ident!r}")
        if ident in ids:
            problems.append(f"{name}: CFBundleIdentifier duplicates {ids[ident]}")
        ids[ident] = name
        for k in ("IATemplateHeaderHeight", "IATemplateFooterHeight"):
            v = info.get(k)
            if v is not None and not (isinstance(v, (int, float)) and 0 <= v <= 400):
                problems.append(f"{name}: {k} must be a number from 0 to 400, got {v!r}")
        for k in ("CFBundleShortVersionString", "CFBundleVersion"):
            if k not in info:
                problems.append(f"{name}: Info.plist lacks {k}")

        res = resources(b)
        pages = {}
        for k in PAGE_KEYS:
            if k in info:
                page = res / (info[k] + ".html")
                if "." in info[k] or "/" in info[k]:
                    problems.append(f"{name}: {k} must be a bare name without extension")
                if not page.exists():
                    problems.append(f"{name}: {k} names missing {page.name}")
                pages[k] = page
        for page in res.glob("*.html"):
            if page not in pages.values():
                problems.append(f"{name}: {page.name} is not named in Info.plist")
            text = page.read_text(encoding="utf-8")
            p = RefParser()
            p.feed(text)
            p.close()
            for e in p.errors:
                problems.append(f"{name}/{page.name}: {e}")
            if p.stack and p.stack != ["html"]:
                problems.append(f"{name}/{page.name}: unclosed {p.stack}")
            if not text.lstrip().lower().startswith("<!doctype html>"):
                problems.append(f"{name}/{page.name}: missing <!DOCTYPE html> (quirks mode)")
            unknown = p.data_attrs - ALLOWED_DATA
            if unknown:
                problems.append(f"{name}/{page.name}: iA Writer does not fill {sorted(unknown)}")
            is_doc = page == pages.get("IATemplateDocumentFile")
            if is_doc and not p.has_document:
                problems.append(f"{name}/{page.name}: no data-document element")
            if not is_doc and "data-page-number" in p.data_attrs and page == pages.get("IATemplateTitleFile"):
                problems.append(f"{name}/{page.name}: data-page-number is not available on the title page")
            if re.search(r"""<html[^>]*\bclass=""", text):
                problems.append(f"{name}/{page.name}: iA Writer overwrites <html class>; use an id")

        for ref in referenced_files(res):
            if ".." in Path(ref).parts or ref.startswith("/"):
                problems.append(f"{name}: reference escapes the bundle: {ref}")
            elif not (res / ref).exists():
                problems.append(f"{name}: referenced file missing: {ref}")
            elif (SHARED / ref).exists() and (res / ref).read_text(encoding="utf-8") != generated_text(SHARED / ref):
                problems.append(f"{name}: {ref} differs from shared/{ref}; run tools/build.py")
        for f in res.rglob("*"):
            if f.name == ".DS_Store":
                problems.append(f"{name}: stray {f.relative_to(b)}")
    return problems


def bump(part):
    for b in bundles():
        path = b / "Contents" / "Info.plist"
        with path.open("rb") as fh:
            info = plistlib.load(fh)
        nums = [int(x) for x in str(info.get("CFBundleShortVersionString", "1.0.0")).split(".")]
        nums += [0] * (3 - len(nums))
        i = {"major": 0, "minor": 1, "patch": 2}[part]
        nums[i] += 1
        nums[i + 1:] = [0] * (2 - i)
        info["CFBundleShortVersionString"] = ".".join(map(str, nums))
        info["CFBundleVersion"] = str(int(info.get("CFBundleVersion", "0")) + 1)
        with path.open("wb") as fh:
            plistlib.dump(info, fh, sort_keys=False)
        print(f"{b.name}: {info['CFBundleShortVersionString']} ({info['CFBundleVersion']})")


def make_zips():
    DIST.mkdir(exist_ok=True)
    for b in bundles():
        out = DIST / f"{b.name}.zip"
        with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
            for f in sorted(b.rglob("*")):
                if f.is_file() and f.name != ".DS_Store":
                    z.write(f, f.relative_to(ROOT))
        print(f"wrote   {out.relative_to(ROOT)}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="check only, do not sync")
    ap.add_argument("--bump", choices=("major", "minor", "patch"))
    ap.add_argument("--zip", action="store_true")
    args = ap.parse_args()
    if args.bump:
        bump(args.bump)
    if not args.check:
        sync()
    problems = check()
    for p in problems:
        print("PROBLEM", p)
    if problems:
        return 1
    print(f"OK      {len(bundles())} bundles")
    if args.zip:
        make_zips()
    return 0


if __name__ == "__main__":
    sys.exit(main())
